import {chromium} from 'playwright';import fs from 'fs';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import crypto from 'node:crypto';
import {simulate,fireWeapon} from '../dist/game/game_logic.js';
const db=new DatabaseSync('/tmp/work/cloud/.wrangler/state/v3/d1/miniflare-D1DatabaseObject/701f968ee2e4c14854057240f87d7e5c139584e939f53a80de85355463c3f94e.sqlite');
db.prepare("update matches set status='aborted' where status in ('active','waiting')").run();
db.prepare("update user_items set qty=30 where user_id=1 and item_id in ('piercing_shell','emp_shell')").run();
const setting=db.prepare("select value from settings where key='gameplay_controls'").get();const controls=JSON.parse(setting?.value||'{}');controls.dynamic_obstacle={...(controls.dynamic_obstacle||{}),enabled:false};controls.weapon_cooldowns={...(controls.weapon_cooldowns||{}),shot_clock:120};db.prepare("insert into settings(key,value) values('gameplay_controls',?) on conflict(key) do update set value=excluded.value").run(JSON.stringify(controls));
let uid=db.prepare('select id from users where email=?').get('opponent66@test.local')?.id;
if(!uid){db.prepare('insert into users(email,name,coins,rating,created_at) values(?,?,?,?,?)').run('opponent66@test.local','Opponent QA',10000,1000,new Date().toISOString());uid=db.prepare('select id from users where email=?').get('opponent66@test.local').id;}
const token=crypto.randomUUID();db.prepare('insert into sessions(user_id,token_hash,created_at,expires_at) values(?,?,?,?)').run(uid,crypto.createHash('sha256').update(token).digest('hex'),new Date().toISOString(),new Date(Date.now()+86400000).toISOString());
const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',args:['--no-sandbox','--enable-unsafe-swiftshader'],headless:true});const errors=[];
const login=async(tok,mobile)=>{const c=await b.newContext({viewport:mobile?{width:390,height:844}:{width:1280,height:720},isMobile:mobile,hasTouch:mobile});const p=await c.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('http://localhost:8799');await p.click('#consent-essential');await p.evaluate(t=>{API.setToken(t);Consent.setPref('bg_tutorial_done','1');Consent.setPref('brigagame_lang','he')},tok);await p.reload();await p.waitForFunction(()=>App.me);if(await p.locator('#nick-skip').isVisible())await p.click('#nick-skip');await p.evaluate(()=>{location.hash='#/lobby';Clockwork.mode=()=>"full"});await p.waitForSelector('#friend-btn');await p.waitForTimeout(250);if(await p.locator('#nick-skip').isVisible())await p.click('#nick-skip');return p;};
const p=await login(fs.readFileSync('/tmp/qatok','utf8'),true),q=await login(token,false);
const friendResponse=p.waitForResponse(r=>r.url().endsWith('/api/matches/friend')&&r.request().method()==='POST');await p.click('#friend-btn');const code=(await (await friendResponse).json()).code;assert.ok(code);await q.fill('#join-code',code);await q.click('#join-btn');await p.waitForSelector('#game-canvas');await q.waitForSelector('#game-canvas');await p.waitForFunction(()=>__game?.snap?.status==='active');await q.waitForFunction(()=>__game?.snap?.status==='active');await p.evaluate(()=>{__game._clockAutoFired=true;__game.snap.turn_deadline=Date.now()/1000+120});await q.evaluate(()=>{__game._clockAutoFired=true;__game.snap.turn_deadline=Date.now()/1000+120});
const id=await p.evaluate(()=>__game.matchId);console.log('HVH GUI join',id,code);
for(const weapon of ['piercing_shell','emp_shell']){
await p.evaluate(()=>__game.refresh(0));const state=JSON.parse(db.prepare('select state from matches where id=?').get(id).state);const live=await p.evaluate(()=>__game.snap);Object.assign(state,{wind:live.wind,obstacle:live.obstacle,towers:live.towers,tower_x:live.tower_x});console.log('QA state',state.wind,state.obstacle_motion,state.cooldowns);let aim;
for(let a=8;a<80&&!aim;a++)for(let pow=20;pow<=100&&!aim;pow++){const ev=[];simulate(state,'p1',a,pow,weapon,ev,'p2');if(ev.some(e=>e.side==='p2' && (e.type==='piercing_impact'||e.type==='emp_impact'))){if(weapon==='piercing_shell'){const temp=structuredClone(state),[e]=fireWeapon(temp,'p1',a,pow,weapon,()=>.5);if(e.find(x=>x.type==='piercing')?.cells.length!==2)continue;}aim={a,pow};}}
assert.ok(aim);const before=db.prepare('select qty from user_items where user_id=1 and item_id=?').get(weapon).qty;
if(weapon==='emp_shell'){console.log('sides',await p.evaluate(()=>__game.snap.you),await q.evaluate(()=>__game.snap.you));const shieldResp=q.waitForResponse(r=>r.url().endsWith('/shield'));await q.click('#shield-btn');console.log('shieldresponse',(await (await shieldResp).json()).shield);}
await p.locator('#weapon-bar .wpn').filter({hasText:weapon==='emp_shell'?'EMP':'חודר'}).click();await p.evaluate(({a,pow})=>{__game.aimAngle=a;__game.aimPower=pow},aim);await p.waitForFunction(()=>__game.canFire());console.log('pre-fire',weapon,await p.evaluate(()=>({wind:__game.snap.wind,deadline:__game.snap.turn_deadline})));const response=p.waitForResponse(r=>r.url().endsWith('/fire')&&r.request().method()==='POST');await p.keyboard.press('Space');const r=await response;assert.equal(r.status(),200);const data=await r.json();console.log(weapon,'impact',aim,data.events.filter(e=>['piercing','emp','explosion'].includes(e.type)));assert.equal(db.prepare('select qty from user_items where user_id=1 and item_id=?').get(weapon).qty,before-1);
if(weapon==='piercing_shell')assert.equal(data.events.find(e=>e.type==='piercing').cells.length,2);
else{assert.ok(data.emp_disabled_until.p2>Date.now()/1000);await q.waitForFunction(()=>document.querySelector('#shield-btn').textContent.includes('מושבת'));assert.equal(await q.locator('#shield-btn').isDisabled(),true);const block=await q.evaluate(id=>API.post(`/api/matches/${id}/shield`),id);assert.equal(block.data.error,'emp_disabled');await p.waitForTimeout(1000);await q.screenshot({path:'/downloads/qa66-emp-opponent.png'});await q.waitForFunction(()=>!document.querySelector('#shield-btn').textContent.includes('מושבת'));console.log('EMP recovery GUI PASS');}
await p.waitForTimeout(1800);for(const[w,h]of[[1280,720],[390,844]]){await p.bringToFront();await p.setViewportSize({width:w,height:h});await p.waitForFunction(()=>{const a=__game.canvas.getBoundingClientRect(),g=document.getElementById('gl3d-canvas')?.getBoundingClientRect();return g&&['x','y','width','height'].every(k=>Math.abs(a[k]-g[k])<1)});const v=await p.evaluate(()=>{const a=__game.canvas.getBoundingClientRect(),g=document.getElementById('gl3d-canvas')?.getBoundingClientRect();return{a:a.toJSON(),g:g?.toJSON(),mode:__game._r3d}});assert.ok(v.g);console.log('RECT',weapon,w,v);for(const k of['x','y','width','height'])assert.ok(Math.abs(v.a[k]-v.g[k])<1);console.log(weapon,w,'2D3D rect PASS');await p.screenshot({path:`/downloads/qa66-${weapon}-${w}.png`});}}
await p.setViewportSize({width:390,height:844});await p.bringToFront();await p.click('#exit-match-btn');await p.click('#exit-match-yes');await p.waitForFunction(()=>location.hash==='#/lobby');assert.deepEqual(errors,[]);await b.close();console.log('weapons GUI combat, ammo, EMPwarning/shield enforcement/resize, exit PASS');
